"""
Dual report generator.

sanitized report  → findings/<id>/report.md      (Claude reads, platform gets)
full report       → ~/.hive/<prog>/findings/<id>/report_full.md  (local only)

The full report has all <SAFE:id> tokens substituted with real values
from the vault. It never goes to Claude.
"""

import os
import re
from datetime import datetime, timezone
from pathlib import Path

from config import BB_ROOT, VAULT_ROOT
from vault.safe import resolve_all, store_finding
from audit import logger as audit
from core.sanitizer import sanitize as _sanitize_text


# Match both <SAFE:id> (legacy) and <SAFE:type:id> (current sanitizer format).
# Optional type group is non-capturing; the 8-hex id is the substitution key.
_SAFE_TOKEN = re.compile(r'<SAFE:(?:[^:>]+:)?([a-f0-9]{8})>')


def _substitute_tokens(text: str, vault_map: dict[str, str]) -> str:
    """Replace <SAFE:[type:]id> tokens with real values from the vault map."""
    def replace(m: re.Match) -> str:
        safe_id = m.group(1)
        return vault_map.get(safe_id, m.group(0))
    return _SAFE_TOKEN.sub(replace, text)


def generate(
    program: str,
    finding_id: str,
    title: str,
    vuln_type: str,
    intigriti_type: str,
    asset_url: str,
    asset_tier: str,
    asset_type: str,
    cvss_vector: str,
    cvss_score: float,
    severity: str,
    cwe: str,
    description: str,
    steps: list[str],
    poc_request: str,
    poc_response: str,
    poc_curl: str,
    impact: str,
    remediation: str,
    references: list[str],
) -> tuple[str, str]:
    """
    Generate both report versions.

    Returns:
        (sanitized_path, full_path)
    """
    date_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    # ── Backstop sanitization on free-text inputs ─────────────────────────────
    # Inputs are typically pre-sanitized (Claude pastes from already-vaulted MCP
    # output), but a typo or raw paste could leak real PII / tokens into the
    # sanitized report. Run them through the same sanitizer the MCP uses.
    description  = _sanitize_text(description,  program, 'create_report:description')
    poc_request  = _sanitize_text(poc_request,  program, 'create_report:poc_request')
    poc_response = _sanitize_text(poc_response, program, 'create_report:poc_response')
    poc_curl     = _sanitize_text(poc_curl,     program, 'create_report:poc_curl')
    impact       = _sanitize_text(impact,       program, 'create_report:impact')
    remediation  = _sanitize_text(remediation,  program, 'create_report:remediation')
    title        = _sanitize_text(title,        program, 'create_report:title')
    steps        = [_sanitize_text(s, program, 'create_report:step') for s in steps]

    # ── Build sanitized report ─────────────────────────────────────────────────

    steps_md = '\n'.join(f'{i+1}. {s}' for i, s in enumerate(steps))
    refs_md  = '\n'.join(f'- {r}' for r in references)

    sanitized = f"""# {title}

**Finding ID:** {finding_id}
**Date:** {date_str}
**Program:** {program}

---

## Summary

**Asset:** `{asset_url}`
**Asset Tier:** {asset_tier}
**Asset Type:** {asset_type}
**Vulnerability Type:** {vuln_type}
**Intigriti Type:** {intigriti_type}
**CWE:** {cwe}
**CVSS 3.1:** {cvss_score} ({severity}) — `{cvss_vector}`

---

## Description

{description}

---

## Steps to Reproduce

{steps_md}

---

## Proof of Concept

### HTTP Request
```http
{poc_request}
```

### HTTP Response
```http
{poc_response}
```

### cURL Command (copy-paste ready)
```bash
{poc_curl}
```

---

## Impact

{impact}

---

## Recommended Solution

{remediation}

---

## References

{refs_md}

---

## Duplicate Risk

Duplicate Risk: [Low / Medium / High]
Reasoning: [fill before submission]

---

*Report generated by bb-mcp-server. Sensitive values replaced with vault tokens.*
*Full report with real values: ~/.hive/{program}/findings/{finding_id}/report_full.md*
"""

    # ── Build full report (real values substituted) ───────────────────────────

    vault_map = resolve_all(program)
    full = _substitute_tokens(sanitized, vault_map)

    # Remove the vault token notice from full report
    full = full.replace(
        '*Report generated by bb-mcp-server. Sensitive values replaced with vault tokens.*\n',
        ''
    )
    full = full.replace(
        f'*Full report with real values: ~/.hive/{program}/findings/{finding_id}/report_full.md*\n',
        ''
    )
    full = f'<!-- FULL REPORT — CONTAINS REAL VALUES — LOCAL ONLY -->\n\n' + full

    # ── Build repro script ────────────────────────────────────────────────────

    repro_sanitized = f'#!/bin/bash\n# PoC for {finding_id} — {title}\n\n{poc_curl}\n'
    repro_full = _substitute_tokens(repro_sanitized, vault_map)

    # ── Write sanitized report ────────────────────────────────────────────────

    finding_dir = BB_ROOT / 'programs' / program / 'findings' / finding_id
    finding_dir.mkdir(parents=True, exist_ok=True)

    poc_dir = finding_dir / 'poc'
    poc_dir.mkdir(exist_ok=True)

    sanitized_path = finding_dir / 'report.md'
    sanitized_path.write_text(sanitized, encoding='utf-8')

    repro_path = poc_dir / 'repro.sh'
    repro_path.write_text(repro_sanitized, encoding='utf-8')
    # 0o700 — owner-only. Sanitized PoC has no real values, but least-privilege
    # is the right default; operator runs the script as themselves.
    os.chmod(repro_path, 0o700)

    # ── Write full report to vault (chmod 600, operator only) ─────────────────

    import traceback as _tb
    try:
        store_finding(program, finding_id, full, repro_full)
    except Exception as _e:
        Path('/tmp/mcp_store_error.log').write_text(
            f'store_finding failed:\n{_tb.format_exc()}\n'
        )
        raise

    audit.log(program, 'report_generated', {
        'finding_id':      finding_id,
        'title':           title,
        'severity':        severity,
        'cvss':            cvss_score,
        'sanitized_path':  str(sanitized_path),
    })

    full_report_path = VAULT_ROOT / program / 'findings' / finding_id / 'report_full.md'
    return str(sanitized_path), str(full_report_path)
